# Generated by Django 3.1.5 on 2021-02-19 15:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subdivisions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Фио работника')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('salary', models.PositiveSmallIntegerField(default=0, help_text='Ставка указывается в рублях', verbose_name='Ставка')),
                ('recruitment_date', models.DateField(default=datetime.date.today, verbose_name='Дата приема на работу')),
                ('dismissal_point', models.BooleanField(default=True, verbose_name='Находится в штате')),
                ('subdivision', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subdivisions.subdivision', verbose_name='Подразделение')),
                ('user_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Dismissal_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissal_date', models.DateField(default=datetime.date.today, verbose_name='Дата увольнения')),
                ('worker_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker', verbose_name='Фио работника')),
            ],
            options={
                'verbose_name': 'Увольнение',
                'verbose_name_plural': 'Увольнения',
            },
        ),
    ]
