# Generated by Django 3.1.5 on 2021-02-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_dismissal_list_dismissal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dismissal_list',
            name='dismissal',
            field=models.CharField(max_length=8, verbose_name='Приказ об увольнении'),
        ),
    ]
